import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LoginBtn from "./login/LoginBtn";
import LogoutBtn from "./login/LogoutBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Next Step
          </Link>
          <Link href="/list">List</Link>
          {!session ? ( // 로그인이 되어있을 때
            <LoginBtn></LoginBtn>
          ) : (
            <LogoutBtn></LogoutBtn>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
